#!/usr/bin/env python3
"""veldo lander: land a completed build to the trunk, serialized across the fleet.

When a worker finishes building a spec on its own branch, the built work has to reach the
trunk without colliding with the other workers landing at the same moment. The lander makes
that safe with three guarantees:

  1. SERIALIZED. A single fleet-wide land lock (a well-known unit in the claim ledger,
     WARP-0701) means only one land runs at a time. The lock is acquired by waiting, held
     with a heartbeat so a long land never looks dead, and released in a finally so a crash
     never wedges the trunk. A fast-forward-only push is the correctness backstop: even if
     the lock were ever stolen from a stalled holder, a stale push simply fails rather than
     clobbering the trunk.

  2. MERGE, NOT REWRITE. The build is MERGED (not cherry-picked), so the build's
     implementation and evidence commits keep their shas - which is what keeps the proof and
     verdict, both digest-bound to the implementation commit, valid after landing. The trunk
     may have advanced since the build started (a prior land); the merge replays the build onto
     it, union-resolving the known shared APPEND-ONLY files (the selftest, the capability
     catalogs, the event log) and regenerating the spec index, while a conflict in any OTHER
     file is a real conflict that the build must resolve itself - the lander rejects it rather
     than guessing.

  3. A DISPOSABLE CANDIDATE, NEVER THE CALLER'S TRUNK (VELDO-0056, PLAN-0019 W41, R48, R76).
     Every land builds its candidate in a dedicated detached workspace: a new repository
     (git init with no template) whose object store borrows the caller repository's objects
     through Git alternates, as VELDO-0042's worker clones do, so it shares no refs, no index,
     no HEAD, no configuration and no worktree link with the caller. Nothing checks out, moves
     or even fetches into the caller's trunk, so another worktree holding the trunk, or a trunk
     with any name, changes nothing. Construction, in order (sync_main, then reconcile):

       the watermark  the published trunk tip, fetched once into the workspace (or, with push
                      disabled, the caller's local trunk tip, read and never written). Every
                      later step uses that exact commit: it is the candidate's fixed input.
       implementation the commit the unit's proof names (proof/<unit>/manifest.json at the
                      evidence commit), required to exist and to be an ancestor of the evidence
                      commit, merged first with --no-ff.
       evidence       the built commit the build ref names, merged second, so the candidate
                      keeps distinct implementation and evidence ancestry.
       projections    each derived file (specs/index.md) regenerated by the candidate's own
                      generator from the merged tree, and committed. The candidate is then
                      required clean.

     Every Git operation on that path goes through one checked step, so a failed fetch, merge,
     object lookup, index write or commit refuses the candidate by name (the failing operation
     is in the refusal), and missing required evidence refuses it before anything is merged.
     The gate runs in the candidate and is green only on exit 0 with a terminal GREEN line for
     the candidate commit. finalize then asks the policy about that exact candidate. For a
     factory land it is the authority's CandidatePolicy, installed code outside the candidate
     (R50): the accepted proof (VELDO-0050), the review obligations (VELDO-0049) and the
     publication decision over the candidate workspace (VELDO-0052). A pre-factory land with no
     authority policy wired asks the repository policy (policy_check.py) at the candidate, over
     exactly watermark..candidate. Only after the policy accepts does anything move: the exact
     candidate commit is pushed, fast-forward only. Every refusal leaves the caller's
     refs, HEAD, index and working bytes, and the remote trunk, exactly as they were, and the
     workspace is removed at the end of every land. Local trunk synchronization, exact-tip
     publication and the completion receipt are VELDO-0057's; a kill or restart during
     construction and competing landers are Release 2.

The lander's control logic (lock, serialize, stage order, abort-and-release, ff-push guard)
is mechanical and gate-tested over a fake LandOps with no real git; the real git steps live in
GitLandOps. Pure stdlib; Unix-only via the claim ledger."""

# Load the shared Git boundary by sibling path, including when imported by file location.
import importlib.util as _git_importlib
from pathlib import Path as _GitPath
_git_spec = _git_importlib.spec_from_file_location("veldo_git_process", _GitPath(__file__).resolve().with_name("git_process.py"))
_git_process = _git_importlib.module_from_spec(_git_spec)
_git_spec.loader.exec_module(_git_process)
import hashlib
import importlib.util
import json
import os
import shutil
import subprocess
import sys
import tempfile
import threading
import time
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LAND_LOCK_UNIT = "__land_lock__"


def _load(name, rel):
    spec = importlib.util.spec_from_file_location(name, ROOT / rel)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


CL = _load("veldo_claim_ld", ".veldo/claim.py")

# The shared APPEND-ONLY files two lands can both touch: a union merge keeps both sides'
# additions. Everything else that conflicts is a real conflict the lander refuses to guess at.
UNION_PATHS = (
    "scripts/selftest.py",
    ".veldo/capabilities.yaml",
    "engine/.veldo/capabilities.yaml",
    ".veldo/events.jsonl",
)
# The candidate's projections: each derived path and the generator in the candidate tree that
# derives it from the candidate's own merged tree. Regenerated deterministically after the merges
# rather than merged line by line.
PROJECTIONS = (("specs/index.md", "scripts/update_index.py"),)
REGEN_PATHS = tuple(path for path, _generator in PROJECTIONS)

CANDIDATE_SCHEMA = "veldo.landing_candidate/v1"
MANIFEST_PATH = "proof/%s/manifest.json"
GATE_COMMAND = ("bash", "scripts/verify.sh")
POLICY_COMMAND = (".veldo/policy_check.py",)
# The workspace's own refs: the fixed watermark, and the trunk the repository policy compares the
# candidate with (it reads origin/HEAD), whatever the caller's trunk and remote are named.
WATERMARK_REF = "refs/veldo/candidate/watermark"
POLICY_BASE_REF = "refs/remotes/origin/%s"
POLICY_HEAD_REF = "refs/remotes/origin/HEAD"
GIT_SECONDS = 120
STEP_SECONDS = 600

# The error taxonomy every refusal code maps to (observability). Unknown is never success.
TAXONOMY = {
    "invalid_input": "invalid_input", "missing_authority": "missing_authority",
    "missing_evidence": "missing_evidence", "stale_subject": "stale_subject", "stale_input": "stale_subject",
    "stale_proof": "stale_subject", "binding_mismatch": "stale_subject", "conflict": "stale_subject",
    "union_unsafe": "stale_subject", "unavailable_service": "unavailable_service",
    "not_handed_off": "missing_authority", "unresolved_finding": "missing_evidence",
    "awaiting_reviews": "missing_evidence", "stale_claim": "stale_subject", "stale_scope": "stale_subject",
    "stale_authority": "stale_subject", "blocked": "missing_authority", "draft_plan": "missing_authority",
    "unresolved_dependency": "missing_evidence", "clock_uncertain": "unknown_outcome",
}


def taxonomy(code):
    """The error class of a refusal code; a code with no class is an unknown outcome, never success."""
    return TAXONOMY.get(str(code).split(":", 1)[0], "unknown_outcome")


class LandOps:
    """The steps a land runs through, as a seam so the control logic is testable without git.
    Each returns {ok: bool, ...}. GitLandOps runs them for real; a fake drives the tests."""

    def sync_main(self):
        """Fix the trunk this land builds on (the watermark)."""
        raise NotImplementedError

    def reconcile(self, unit):
        """Build the candidate: merge the build onto the watermark, union-resolving shared
        append-only files and rejecting a real conflict (ok False with the conflicting paths)."""
        raise NotImplementedError

    def gate(self):
        """Run the gate on the candidate."""
        raise NotImplementedError

    def finalize(self, unit):
        """Policy-check and fast-forward-only push. ok False if the push was rejected."""
        raise NotImplementedError


class Lander:
    """The serialized land: acquire the land lock, run the steps, release the lock. The lock
    is held with a heartbeat so a long land never looks stale, and released in a finally."""

    def __init__(self, worker_id, ops, claims_root=None, lock_timeout=600.0,
                 poll=0.02, hb_interval=None):
        self.worker_id = worker_id
        self.ops = ops
        self.claims_root = claims_root
        self.lock_timeout = lock_timeout
        self.poll = poll
        # heartbeat well under the ledger's staleness threshold so the lock stays live
        self.hb_interval = hb_interval if hb_interval is not None else CL.STALE_AFTER_SECONDS / 3.0
        self._hb_stop = None
        self._hb_thread = None
        self._hb_error = None

    def _heartbeat_loop(self):
        # wait() returns True when signalled to stop, False on timeout (time to heartbeat)
        while not self._hb_stop.wait(self.hb_interval):
            try:
                if not CL.heartbeat(LAND_LOCK_UNIT, self.worker_id, root=self.claims_root):
                    raise CL.ClaimStopped('ownership_uncertain')
            except CL.ClaimStopped as exc:
                self._hb_error = exc
                return
            except Exception:
                # a transient error (a brief filesystem hiccup) must not kill the keep-alive,
                # or the lock could silently go stale mid-land; just retry on the next tick.
                pass

    def _acquire(self):
        """Wait until the land lock is ours, then start heartbeating it. False on timeout."""
        start = time.monotonic()
        while True:
            ok, _reason = CL.claim(LAND_LOCK_UNIT, self.worker_id, [], [], root=self.claims_root)
            if ok:
                self._hb_error = None
                self._hb_stop = threading.Event()
                self._hb_thread = threading.Thread(target=self._heartbeat_loop, daemon=True)
                self._hb_thread.start()
                return True
            if time.monotonic() - start > self.lock_timeout:
                return False
            time.sleep(self.poll)

    def _release(self):
        if self._hb_stop is not None:
            self._hb_stop.set()
        if self._hb_thread is not None:
            self._hb_thread.join(timeout=5.0)
        self._hb_stop = None
        self._hb_thread = None
        CL.release(LAND_LOCK_UNIT, self.worker_id, root=self.claims_root)

    def _check_ownership(self):
        if self._hb_error is not None:
            raise self._hb_error
        client = CL._authority(self.claims_root)
        owned = (client.use(LAND_LOCK_UNIT) if client else
                 CL.holder(LAND_LOCK_UNIT, root=self.claims_root) == self.worker_id)
        if not owned:
            raise CL.ClaimStopped('ownership_uncertain')

    def land(self, unit=None):
        """Land the built unit to the trunk under the land lock. Returns {ok, stage, detail}.
        A failing stage aborts the land (later stages do not run) and the lock is always
        released. Stages run in order: sync_main, reconcile, gate, finalize. The ops' candidate
        workspace, when it keeps one, is discarded however the land ends."""
        if not self._acquire():
            return {"ok": False, "stage": "lock"}
        try:
            stages = (
                ("sync_main", lambda: self.ops.sync_main()),
                ("reconcile", lambda: self.ops.reconcile(unit)),
                ("gate", lambda: self.ops.gate()),
                ("finalize", lambda: self.ops.finalize(unit)),
            )
            for name, fn in stages:
                if name == 'finalize':
                    # Join the heartbeat before the final use so a named stop cannot
                    # race the publication check or be overwritten by cleanup.
                    self._hb_stop.set()
                    self._hb_thread.join()
                    self._check_ownership()
                r = fn() or {}
                if not r.get("ok"):
                    return {"ok": False, "stage": name, "detail": r}
            return {"ok": True, "stage": "landed"}
        finally:
            stopping = sys.exc_info()[0] is not None
            discard = getattr(self.ops, "discard", None)
            if callable(discard):
                discard()
            try:
                self._release()
            except CL.ClaimStopped:
                if not stopping:
                    raise


class CandidateRefused(Exception):
    """A named refusal of one candidate step: nothing outside the disposable workspace changed.
    `operation` is the Git subcommand (or step) that failed, when one did."""

    def __init__(self, code, detail="", operation=None, **extra):
        super().__init__(code + (": " + detail if detail else ""))
        self.code, self.detail, self.operation, self.extra = code, detail, operation, extra


def _hex(value):
    return isinstance(value, str) and len(value) in (40, 64) and set(value) <= set("0123456789abcdef")


def _text(value):
    return isinstance(value, str) and bool(value.strip())


def _digest(body):
    return "sha256:" + hashlib.sha256(body).hexdigest()


def _first_line(text):
    lines = [line for line in (text or "").splitlines() if line.strip()]
    return lines[0][:300] if lines else ""


def _unit_id(unit):
    if isinstance(unit, dict):
        return unit.get("spec") if _text(unit.get("spec")) else None
    return unit if _text(unit) else None


class GitLandOps(LandOps):
    """Real git land through a disposable candidate: fix the watermark, merge the unit's
    implementation and evidence in a dedicated detached workspace, regenerate the projections,
    gate the candidate, ask the policy, and only then push the exact candidate commit,
    fast-forward only.

    repo_root   the caller's repository, read and never written: its objects (borrowed through
                alternates), the build ref and, with push disabled, its local trunk tip.
    build_ref   the evidence commit, or a ref naming it, in the caller's repository.
    trunk       the trunk's branch name, whatever it is; remote the caller's remote for it.
    push        False builds, gates and accepts the candidate but publishes nothing.
    policy      the authority's acceptance, called (unit, candidate) -> {ok, refusals}: for a
                factory land a CandidatePolicy. With none, the repository policy
                (policy_check.py at the candidate) decides, as a pre-factory land always has.
    identity    (name, email) the candidate's merge and projection commits are made as; by
                default the caller repository's own configured user.name and user.email.
    workspace_root  where candidate workspaces are made (the system temporary directory).
    observe     receives one event per stage: operation, repository, unit, candidate, the
                accepted input versions, outcome, named refusal and its taxonomy."""

    def __init__(self, repo_root, build_ref, trunk="main", remote="origin", push=True, *,
                 policy=None, identity=None, workspace_root=None, observe=None, domain=None,
                 repository=None):
        self.repo_root = str(repo_root)
        self.build_ref = build_ref
        self.trunk = trunk
        self.remote = remote
        self.push = push
        self.policy = policy
        self.identity = tuple(identity) if identity is not None else None
        self.workspace_root = str(workspace_root) if workspace_root is not None else None
        self.observe = observe or (lambda event: None)
        self.domain = domain
        self.repository = repository
        self.counts = {"accepted": 0, "refused": 0}
        self.candidate = None

    # -- the one checked Git step --------------------------------------------------------------

    def _git(self, repo, *args, operation=None, profile="isolated", ok=(0,), text=True, identity=None):
        """Run one Git operation in `repo` through the boundary. A return code outside `ok` refuses
        the candidate naming the operation; the completed process is returned otherwise."""
        name = operation or args[0]
        try:
            result = _git_process.run(["git", "-C", str(repo), *args], capture_output=True, text=text,
                                      timeout=GIT_SECONDS, stdin=subprocess.DEVNULL, profile=profile,
                                      identity=identity)
        except (OSError, subprocess.SubprocessError) as error:
            raise CandidateRefused("unavailable_service:git/" + name, type(error).__name__, operation=name)
        if ok is not None and result.returncode not in ok:
            stderr = result.stderr if isinstance(result.stderr, str) else (result.stderr or b"").decode("utf-8", "replace")
            raise CandidateRefused("unavailable_service:git/" + name, _first_line(stderr), operation=name)
        return result

    def _absolute(self, url):
        """A remote given as a relative local path is relative to the caller, never to the workspace."""
        if "://" in url or os.path.isabs(url) or ":" in url.split("/", 1)[0]:
            return url
        return str((Path(self.repo_root) / url).resolve())

    def _commit_of(self, repo, revision, missing):
        """The exact commit `revision` names in `repo`; `missing` is the refusal when it names none."""
        found = self._git(repo, "rev-parse", "--verify", "--quiet", revision + "^{commit}", ok=(0, 1))
        value = found.stdout.strip()
        if found.returncode == 1 or not _hex(value):
            raise CandidateRefused(missing, revision, operation="rev-parse")
        return value

    def _ancestor(self, repo, older, newer, refusal):
        found = self._git(repo, "merge-base", "--is-ancestor", older, newer, ok=(0, 1))
        if found.returncode == 1:
            raise CandidateRefused(refusal, "%s is not an ancestor of %s" % (older[:12], newer[:12]),
                                   operation="merge-base")

    def _identity(self):
        if self.identity is not None:
            if len(self.identity) != 2 or not all(_text(v) for v in self.identity):
                raise CandidateRefused("invalid_input:identity", "a name and an email")
            return self.identity
        found = []
        for key in ("user.name", "user.email"):
            value = self._git(self.repo_root, "config", "--get", key, ok=(0, 1))
            found.append(value.stdout.strip() if value.returncode == 0 else "")
        if not all(found):
            raise CandidateRefused("missing_authority:identity",
                                   "no identity is configured for the candidate's commits", operation="config")
        return tuple(found)

    # -- observability --------------------------------------------------------------------------

    def _event(self, operation, outcome, refusal=None, **extra):
        c = self.candidate or {}
        event = {"schema": CANDIDATE_SCHEMA, "operation": operation, "domain": self.domain,
                 "repository": self.repository or self.repo_root, "unit": c.get("unit"),
                 "request": c.get("id"), "accepted_versions": {
                     k: c.get(k) for k in ("watermark", "implementation", "evidence", "commit", "tree") if c.get(k)},
                 "outcome": outcome}
        if refusal is not None:
            event.update(refusal=refusal, taxonomy=taxonomy(refusal))
        event.update(extra)
        self.counts["refused" if outcome == "refused" else "accepted"] += 1
        self.observe(event)
        return event

    def _refuse(self, operation, error, **fields):
        if self.candidate is not None:
            self.candidate["state"] = "refused"
            self.candidate["refusal"] = error.code
        self._event(operation, "refused", error.code, detail=error.detail, failed=error.operation)
        return dict(fields, ok=False, refusal=error.code, operation=error.operation, detail=error.detail,
                    taxonomy=taxonomy(error.code), **error.extra)

    def status(self):
        """Metrics: accepted and refused operations, and the pending candidate (constructed, not yet
        decided), if any."""
        c = self.candidate or {}
        pending = [c["id"]] if c.get("state") in ("synced", "built", "verified") else []
        return dict(self.counts, pending=pending)

    def record(self):
        """The current candidate's record: its identity, fixed inputs, merges, projections and state."""
        return json.loads(json.dumps(self.candidate)) if self.candidate is not None else None

    def discard(self):
        """Remove the candidate workspace. A candidate is disposable: nothing is kept after its land."""
        c = self.candidate
        if c and c.get("workspace") and os.path.isdir(c["workspace"]):
            shutil.rmtree(c["workspace"], ignore_errors=True)
            c["discarded"] = not os.path.exists(c["workspace"])

    # -- the stages -----------------------------------------------------------------------------

    def sync_main(self):
        """A new workspace borrowing the caller's objects, holding the watermark checked out detached."""
        self.discard()
        self.candidate = {"schema": CANDIDATE_SCHEMA, "id": "candidate-" + uuid.uuid4().hex[:16], "state": "new",
                          "trunk": self.trunk, "remote": self.remote if self.push else None,
                          "workspace": None, "merges": [], "projections": {}}
        try:
            workspace = Path(tempfile.mkdtemp(prefix="veldo-candidate-", dir=self.workspace_root))
            self.candidate["workspace"] = str(workspace)
            common = self._git(self.repo_root, "rev-parse", "--path-format=absolute", "--git-common-dir").stdout.strip()
            objects = Path(common) / "objects"
            if not common or not objects.is_dir():
                raise CandidateRefused("unavailable_service:git/rev-parse", "the caller has no object store",
                                       operation="rev-parse")
            self._git(workspace, "init", "-q", "--template=")
            info = workspace / ".git" / "objects" / "info"
            info.mkdir(parents=True, exist_ok=True)
            (info / "alternates").write_text(str(objects) + "\n")
            if self.push:
                url = self._git(self.repo_root, "remote", "get-url", self.remote, profile="network").stdout.strip()
                if not url:
                    raise CandidateRefused("unavailable_service:git/remote", "the remote has no url", operation="remote")
                self._git(workspace, "fetch", "-q", "--no-tags", "--no-write-fetch-head", self._absolute(url),
                          "+refs/heads/%s:%s" % (self.trunk, WATERMARK_REF), profile="network")
            else:
                local = self._commit_of(self.repo_root, "refs/heads/" + self.trunk, "missing_evidence:trunk")
                self._git(workspace, "update-ref", WATERMARK_REF, local)
            watermark = self._commit_of(workspace, WATERMARK_REF, "missing_evidence:watermark")
            self._git(workspace, "update-ref", POLICY_BASE_REF % self.trunk, watermark)
            self._git(workspace, "symbolic-ref", POLICY_HEAD_REF, POLICY_BASE_REF % self.trunk)
            self._git(workspace, "checkout", "-q", "--detach", watermark)
            if self._commit_of(workspace, "HEAD", "unavailable_service:git/checkout") != watermark:
                raise CandidateRefused("unavailable_service:git/checkout", "HEAD is not the watermark",
                                       operation="checkout")
            self.candidate.update(state="synced", watermark=watermark)
        except CandidateRefused as error:
            return self._refuse("sync_main", error)
        except OSError as error:
            return self._refuse("sync_main", CandidateRefused("unavailable_service:workspace", type(error).__name__))
        self._event("sync_main", "accepted")
        return {"ok": True, "candidate": self.candidate["id"], "watermark": watermark}

    def _conflicted_paths(self, workspace):
        out = self._git(workspace, "diff", "--name-only", "--diff-filter=U", "-z", operation="diff")
        return [p for p in out.stdout.split("\0") if p.strip()]

    def _union_resolve_one(self, workspace, path):
        """Union-merge a single conflicted append-only file from its index stages so both sides'
        added lines survive with no conflict markers, then stage the result. Returns True on a
        clean union. Returns False WITHOUT writing if the union is not safe - git merge-file
        --union always returns 0 for a text union, so a non-zero code means a binary file (or a
        genuine error), which would otherwise truncate the file to empty; the caller must reject
        the land rather than commit lost content. A side absent (a delete against a change) is
        not a union either. Every stage it reads is a checked Git operation."""
        listed = self._git(workspace, "ls-files", "-u", "-z", "--", path, operation="ls-files")
        stages = {}
        for entry in listed.stdout.split("\0"):
            if "\t" in entry:
                mode_sha_stage, _name = entry.split("\t", 1)
                parts = mode_sha_stage.split()
                if len(parts) == 3:
                    stages[parts[2]] = parts[1]
        if "2" not in stages or "3" not in stages:
            return False
        with tempfile.TemporaryDirectory() as td:
            names = {}
            for stage, label in (("1", "base"), ("2", "ours"), ("3", "theirs")):
                names[label] = os.path.join(td, label)
                body = (self._git(workspace, "cat-file", "blob", stages[stage], text=False).stdout
                        if stage in stages else b"")
                with open(names[label], "wb") as f:
                    f.write(body)
            merged = _git_process.run(["git", "-C", str(workspace), "merge-file", "-p", "--union",
                                       names["ours"], names["base"], names["theirs"]],
                                      capture_output=True, timeout=GIT_SECONDS, stdin=subprocess.DEVNULL)
            if merged.returncode != 0:
                return False
            with open(os.path.join(workspace, path), "wb") as f:
                f.write(merged.stdout)
        self._git(workspace, "add", "--", path)
        return True

    def _generate(self, workspace, path, generator):
        """Regenerate one projection from the workspace's own tree. False when its generator is absent."""
        if not (Path(workspace) / generator).is_file():
            return False
        environment = dict(os.environ, PYTHONDONTWRITEBYTECODE="1")
        try:
            run = subprocess.run([sys.executable, "-B", generator], cwd=str(workspace), capture_output=True,
                                 text=True, timeout=STEP_SECONDS, stdin=subprocess.DEVNULL, env=environment)
        except (OSError, subprocess.SubprocessError) as error:
            raise CandidateRefused("unavailable_service:projection/" + path, type(error).__name__, operation="projection")
        if run.returncode != 0:
            raise CandidateRefused("unavailable_service:projection/" + path, _first_line(run.stderr or run.stdout),
                                   operation="projection")
        return True

    def _merge(self, workspace, commit, message, identity, role):
        """Merge `commit` into the candidate with --no-ff. A real conflict (outside the union and
        projected paths) refuses by its paths; any other failure refuses by operation."""
        merge = self._git(workspace, "merge", "--no-ff", "--no-edit", "-m", message, commit, ok=None,
                          identity=identity)
        if merge.returncode == 0:
            self.candidate["merges"].append({"role": role, "commit": commit,
                                             "merge": self._commit_of(workspace, "HEAD", "unavailable_service:git/merge")})
            return
        conflicts = self._conflicted_paths(workspace)
        if not conflicts:
            raise CandidateRefused("unavailable_service:git/merge", _first_line(merge.stderr or merge.stdout),
                                   operation="merge")
        real = [c for c in conflicts if c not in UNION_PATHS and c not in REGEN_PATHS]
        if real:
            raise CandidateRefused("conflict:" + real[0], "a real conflict the build must resolve",
                                   operation="merge", conflicts=real)
        for path in conflicts:
            if path in UNION_PATHS:
                if not self._union_resolve_one(workspace, path):
                    # an unsafe union (a binary file) is not something to guess at either
                    raise CandidateRefused("union_unsafe:" + path, "the append-only union is not safe",
                                           operation="merge-file", conflicts=[path], reason="union_unsafe")
            else:
                # A projected path is derived once, from the whole merged tree, by _project: the merge
                # keeps the candidate's own side and the projection replaces it. With no generator
                # there is nothing to derive it from, so the conflict is real.
                if not (Path(workspace) / dict(PROJECTIONS)[path]).is_file():
                    raise CandidateRefused("conflict:" + path, "a projection with no generator conflicted",
                                           operation="merge", conflicts=[path])
                self._git(workspace, "checkout", "--ours", "--", path)
                self._git(workspace, "add", "--", path)
        self._git(workspace, "commit", "--no-edit", "-q", identity=identity)
        self.candidate["merges"].append({"role": role, "commit": commit, "resolved": sorted(conflicts),
                                         "merge": self._commit_of(workspace, "HEAD", "unavailable_service:git/commit")})

    def _project(self, workspace, sid, identity):
        """Every projection regenerated from the merged tree at the fixed watermark, then committed."""
        state = {}
        for path, generator in PROJECTIONS:
            if self._generate(workspace, path, generator):
                self._git(workspace, "add", "--", path)
                state[path] = {"generator": generator}
            else:
                state[path] = {"generator": generator, "absent": True}
        staged = self._git(workspace, "diff", "--cached", "--quiet", ok=(0, 1), operation="diff")
        base = self._commit_of(workspace, "HEAD", "unavailable_service:git/rev-parse")
        if staged.returncode == 1:
            self._git(workspace, "commit", "-q", "-m", "Project %s for %s at watermark %s"
                      % (", ".join(sorted(state)), sid, self.candidate["watermark"][:12]), identity=identity)
        head = self._commit_of(workspace, "HEAD", "unavailable_service:git/commit")
        for path in state:
            if not state[path].get("absent"):
                found = self._git(workspace, "rev-parse", "--verify", "--quiet", "HEAD:" + path, ok=(0, 1))
                state[path]["blob"] = found.stdout.strip() if found.returncode == 0 else None
        self.candidate["projections"] = state
        self.candidate["projected_from"] = base
        self.candidate["projection_commit"] = head if head != base else None

    def reconcile(self, unit):
        """The whole candidate: the unit's implementation, then its evidence, then its projections."""
        c = self.candidate
        try:
            if c is None or c.get("state") != "synced":
                raise CandidateRefused("invalid_input:candidate", "no candidate workspace holds a watermark")
            sid = _unit_id(unit)
            if sid is None:
                raise CandidateRefused("invalid_input:unit", "the unit to land is named")
            c["unit"] = sid
            workspace = c["workspace"]
            identity = self._identity()
            evidence = self._commit_of(self.repo_root, str(self.build_ref), "missing_evidence:build_ref")
            path = MANIFEST_PATH % sid
            listed = self._git(workspace, "ls-tree", "-z", evidence, "--", path, operation="ls-tree")
            if not listed.stdout.strip():
                raise CandidateRefused("missing_evidence:proof/" + sid, path + " is absent at the evidence commit")
            body = self._git(workspace, "cat-file", "blob", "%s:%s" % (evidence, path), text=False).stdout
            try:
                manifest = json.loads(body)
            except ValueError:
                manifest = None
            implementation = manifest.get("commit") if isinstance(manifest, dict) else None
            if not _hex(implementation):
                raise CandidateRefused("missing_evidence:implementation", "the proof names no implementation commit")
            kind = self._git(workspace, "cat-file", "-t", implementation, ok=(0, 128), operation="cat-file")
            if kind.returncode != 0 or kind.stdout.strip() != "commit":
                raise CandidateRefused("missing_evidence:implementation/absent", implementation, operation="cat-file")
            self._ancestor(workspace, implementation, evidence, "missing_evidence:implementation/not_ancestor")
            c.update(evidence=evidence, implementation=implementation, proof={"path": path, "digest": _digest(body)})
            self._merge(workspace, implementation, "Land implementation %s of %s" % (implementation[:12], sid),
                        identity, "implementation")
            self._merge(workspace, evidence, "Land evidence %s of %s" % (evidence[:12], sid), identity, "evidence")
            self._project(workspace, sid, identity)
            candidate = self._commit_of(workspace, "HEAD", "unavailable_service:git/rev-parse")
            tree = self._git(workspace, "rev-parse", "--verify", candidate + "^{tree}").stdout.strip()
            dirty = self._git(workspace, "status", "--porcelain", "--untracked-files=all").stdout
            if dirty.strip():
                raise CandidateRefused("invalid_input:candidate/dirty", "the constructed candidate is not clean",
                                       operation="status")
            for older, what in ((c["watermark"], "watermark"), (implementation, "implementation"), (evidence, "evidence")):
                self._ancestor(workspace, older, candidate, "stale_subject:candidate/" + what)
            c.update(state="built", commit=candidate, tree=tree)
        except CandidateRefused as error:
            return self._refuse("reconcile", error)
        except OSError as error:
            return self._refuse("reconcile", CandidateRefused("unavailable_service:workspace", type(error).__name__))
        self._event("reconcile", "accepted")
        return {"ok": True, "candidate": c["commit"], "tree": c["tree"], "watermark": c["watermark"],
                "implementation": c["implementation"], "evidence": c["evidence"]}

    def gate(self):
        """Run the canonical gate in the candidate: green only on exit 0 and a terminal GREEN line
        naming the candidate commit."""
        c = self.candidate
        if c is None or c.get("state") != "built":
            return self._refuse("gate", CandidateRefused("invalid_input:candidate", "no built candidate"))
        try:
            r = subprocess.run(list(GATE_COMMAND), cwd=c["workspace"], capture_output=True, text=True,
                               stdin=subprocess.DEVNULL)
            exit_code, out = r.returncode, r.stdout
        except OSError as error:
            exit_code, out = None, str(error)
        last = [line for line in out.splitlines() if line.strip()][-1:]
        terminal = last[0] if last else None
        green = exit_code == 0 and terminal == "GATE: GREEN (%s)" % c["commit"]
        c["gate"] = {"exit": exit_code, "terminal": terminal, "green": green}
        if not green:
            return self._refuse("gate", CandidateRefused("missing_evidence:gate", str(terminal)),
                                detail_lines=last, exit=exit_code)
        c["state"] = "verified"
        self._event("gate", "accepted", terminal=terminal)
        return {"ok": True, "detail": last, "exit": exit_code, "candidate": c["commit"]}

    def finalize(self, unit):
        """Ask the repository policy and the authority's policy about this exact candidate; only when
        both accept, push the candidate commit to the trunk, fast-forward only."""
        c = self.candidate
        if c is None or c.get("state") != "verified":
            return self._refuse("finalize", CandidateRefused("invalid_input:candidate", "no verified candidate"))
        refusals, detail = [], {}
        if self.policy is None:
            # The pre-factory land: the repository's own policy, asked at the candidate, whose range
            # is exactly watermark..candidate (the workspace's origin/HEAD is the watermark).
            try:
                pc = subprocess.run([sys.executable, "-B", *POLICY_COMMAND], cwd=c["workspace"], capture_output=True,
                                    text=True, stdin=subprocess.DEVNULL,
                                    env=dict(os.environ, PYTHONDONTWRITEBYTECODE="1"))
                policy_out = pc.stdout.strip()
                if pc.returncode != 0:
                    refusals.append("missing_authority:repository_policy")
            except OSError as error:
                policy_out = str(error)
                refusals.append("unavailable_service:repository_policy")
            detail["policy_check"] = policy_out
        else:
            # The factory land: the authority's installed services decide (R50), never the policy code
            # the candidate itself carries.
            try:
                verdict = self.policy(unit, self.record()) or {}
            except Exception as error:  # noqa: BLE001 - a policy that cannot answer accepts nothing
                verdict = {"ok": False, "refusals": ["unavailable_service:policy/" + type(error).__name__]}
            detail["authority"] = verdict
            named = [r for r in verdict.get("refusals") or [] if _text(r)]
            if verdict.get("ok") is not True and not named:
                named = ["unknown_outcome:policy"]
            refusals.extend(named)
        c["policy"] = {"refusals": list(refusals)}
        if refusals:
            error = CandidateRefused(refusals[0], "; ".join(refusals), operation="policy")
            return self._refuse("finalize", error, refusals=refusals, **detail)
        c["state"] = "accepted"
        if not self.push:
            self._event("finalize", "accepted", pushed=False)
            return dict(detail, ok=True, pushed=False, candidate=c["commit"])
        # fast-forward-only push of the exact candidate: if the trunk advanced under us, this fails
        # rather than clobbering it, and the land is retried from sync_main.
        try:
            url = self._git(self.repo_root, "remote", "get-url", "--push", self.remote, profile="network").stdout.strip()
            push = self._git(c["workspace"], "push", "-q", self._absolute(url), "%s:refs/heads/%s" % (c["commit"], self.trunk),
                             profile="network", ok=None)
        except CandidateRefused as error:
            return self._refuse("finalize", error, pushed=False)
        pushed = push.returncode == 0
        c["state"] = "published" if pushed else "rejected"
        self._event("finalize", "accepted" if pushed else "refused",
                    None if pushed else "unavailable_service:git/push", pushed=pushed)
        return dict(detail, ok=pushed, pushed=pushed, candidate=c["commit"], detail=push.stderr.strip())


class CandidatePolicy:
    """The authority's acceptance of one exact candidate, asked by GitLandOps.finalize after the gate
    and before anything moves. Every answer is re-read now, from the store, for this candidate:

      proof        VELDO-0050: the accepted bundle of the unit at the evidence commit the candidate
                   merged, re-derived from Git and its stored observation (control_proof.resolve),
                   naming the implementation commit the candidate merged.
      review       VELDO-0049: the unit's floor record handed off at exactly that evidence commit
                   and proof digest, with no unresolved blocking finding from any attempt.
      publication  VELDO-0052: the publication station's decision, with the CANDIDATE as the
                   Gate's workspace, for the unit's claim holder and generation (approvals, claim,
                   authority, admission scope, decisions, dependencies, blockers, architecture).

    `store` is control_store, `conn` a store connection, `floor` the dispatch.FloorAuthority of this
    repository and `settlement_trust` the Gate's settlement signers. Returns {ok, refusals, ...}."""

    def __init__(self, store, conn, *, domain, repository, floor, settlement_trust=None):
        self.store, self.conn, self.floor = store, conn, floor
        self.domain, self.repository, self.settlement_trust = domain, repository, settlement_trust
        self.CP = _load("veldo_proof_ld", ".veldo/control_proof.py")
        self.EL = _load("veldo_eligibility_ld", ".veldo/control_eligibility.py")

    def __call__(self, unit, candidate):
        sid = _unit_id(unit)
        refusals, answer = [], {}
        if sid is None or not isinstance(candidate, dict) or not _hex(candidate.get("evidence")):
            return {"ok": False, "refusals": ["invalid_input:candidate"]}
        try:
            bundle = self.CP.resolve(self.store, self.conn, domain=self.domain, repository=self.repository,
                                     unit=sid, commit=candidate["evidence"])
            answer["proof"] = bundle.get("bundle")
            if (bundle.get("implementation") or {}).get("commit") != candidate.get("implementation"):
                refusals.append("binding_mismatch:proof/implementation")
        except self.CP.Refused as error:
            refusals.extend(error.codes or [error.code])
        record = self.floor.record(sid) if self.floor is not None else None
        if not isinstance(record, dict):
            refusals.append("missing_authority:floor_record")
        else:
            if record.get("state") != "handoff":
                refusals.append("not_handed_off:%s" % record.get("state"))
            refusals.extend("unresolved_finding:" + fid for fid, f in sorted((record.get("findings") or {}).items())
                            if not (f or {}).get("resolved"))
            if record.get("state") == "handoff":
                # The build handed off is exactly the one this candidate merged: its source and its proof.
                handoff = record.get("handoff") or {}
                if (handoff.get("source") or {}).get("commit") != candidate["evidence"]:
                    refusals.append("binding_mismatch:review/source")
                if (handoff.get("proof") or {}).get("digest") != (candidate.get("proof") or {}).get("digest"):
                    refusals.append("binding_mismatch:review/proof")
        gate = self.EL.Gate(self.store, self.conn, domain_uuid=self.domain, repository_uuid=self.repository,
                            workspace=candidate.get("workspace"), settlement_trust=self.settlement_trust)
        context = {"holder": unit.get("holder"), "generation": unit.get("generation")} if isinstance(unit, dict) else {}
        decision = gate.decide("publication", sid, context=context)
        answer["decision"] = decision.get("decision_id")
        refusals.extend(decision.get("refusals") or [])
        refusals = list(dict.fromkeys(refusals))
        return dict(answer, ok=not refusals, refusals=refusals)


def veldo_land(ops, unit=None, worker_id=None, claims_root=None):
    """Front door: allocate a worker id and land the unit through ops under the land lock."""
    wid = worker_id or ("lander-" + uuid.uuid4().hex[:12])
    return Lander(wid, ops, claims_root=claims_root).land(unit)
